version: "3"
services:
  sender:    
    build: ./Sender
    depends_on:
      - "rabbitmq"
  receiver:    
    build: ./Receiver
    depends_on:
      - "rabbitmq"
  rabbitmq:
    image: "rabbitmq:3-management-alpine"